const { createClient } = require("@supabase/supabase-js");

function db() {
  const url = String(process.env.SUPABASE_URL || "").replace(/\/$/, "");
  const key = String(process.env.SUPABASE_SECRET_KEY || "").trim();
  if (!url || !key) throw new Error("SUPABASE_URL ou SUPABASE_SECRET_KEY manquante.");
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
function clean(value, max=500){ return String(value ?? "").trim().slice(0,max); }
function integer(value, fallback=0){ const n=Number.parseInt(value,10); return Number.isFinite(n)?n:fallback; }
function dateOrNull(value){ if(!value)return null; const d=new Date(value); if(Number.isNaN(d.getTime()))return null; return d.toISOString(); }
function error(message,status=400){ const e=new Error(message); e.status=status; throw e; }
function normalizeRewards(value={}){
  const items=Array.isArray(value.items)?value.items.slice(0,100).map(i=>({classname:clean(i.classname,160),quantity:Math.max(1,Math.min(1000,integer(i.quantity,1)))})).filter(i=>i.classname):[];
  return {items,roubles:Math.max(0,integer(value.roubles,0)),bitcoin:Math.max(0,integer(value.bitcoin,0))};
}
async function seasonById(client,id){ const {data,error:e}=await client.from("battle_pass_seasons").select("*").eq("id",id).maybeSingle(); if(e)throw e; return data; }
async function currentSeason(client){ const {data,error:e}=await client.from("battle_pass_seasons").select("*").order("created_at",{ascending:false}); if(e)throw e; const rows=data||[]; return rows.find(s=>s.status==="active") || rows.find(s=>s.status==="draft") || rows[0] || null; }
async function ensureLevels(client,season){ if(!season)return[]; const {data:existing,error:e}=await client.from("battle_pass_levels").select("*").eq("season_id",season.id).order("level"); if(e)throw e; const map=new Map((existing||[]).map(l=>[l.level,l])); const missing=[]; for(let level=1;level<=season.max_level;level++){ if(!map.has(level))missing.push({season_id:season.id,level,xp_required:(level-1)*season.xp_per_level}); }
  if(missing.length){ const {error:ie}=await client.from("battle_pass_levels").insert(missing); if(ie)throw ie; }
  if((existing||[]).some(l=>l.level>season.max_level)){ const {error:de}=await client.from("battle_pass_levels").delete().eq("season_id",season.id).gt("level",season.max_level); if(de)throw de; }
  const {data,error:fe}=await client.from("battle_pass_levels").select("*").eq("season_id",season.id).order("level"); if(fe)throw fe; return data||[];
}
function computeLevel(season,xp){ if(!season)return 1; const n=Math.max(0,Number(xp)||0); return Math.max(1,Math.min(season.max_level,Math.floor(n/season.xp_per_level)+1)); }
async function dashboard(){ const client=db(); const season=await currentSeason(client); if(!season)return{season:null,levels:[],players:[],stats:{players:0,premiumPlayers:0,averageLevel:0}}; const [levels,{data:players,error:pe}]=await Promise.all([ensureLevels(client,season),client.from("battle_pass_players").select("*").eq("season_id",season.id).order("level",{ascending:false}).order("xp",{ascending:false})]); if(pe)throw pe; const list=players||[]; return {season,levels,players:list,stats:{players:list.length,premiumPlayers:list.filter(p=>p.is_premium).length,averageLevel:list.length?list.reduce((a,p)=>a+Number(p.level||1),0)/list.length:0}}; }
async function saveSeason(input,actor){ const client=db(); const current=await currentSeason(client); const code=clean(input.code,20); const name=clean(input.name,100); if(!code||!name)error("Code et nom de saison obligatoires."); const status=clean(input.status,20)||"draft"; if(!["draft","active","ended"].includes(status))error("Statut de saison invalide."); const maxLevel=Math.max(1,Math.min(200,integer(input.maxLevel??input.max_level,50))); const xpPerLevel=Math.max(1,integer(input.xpPerLevel??input.xp_per_level,1000)); const payload={code,name,description:clean(input.description,1000),status,starts_at:dateOrNull(input.startsAt??input.starts_at),ends_at:dateOrNull(input.endsAt??input.ends_at),max_level:maxLevel,xp_per_level:xpPerLevel,premium_enabled:input.premiumEnabled??input.premium_enabled??true,updated_by:String(actor||"")||null,updated_at:new Date().toISOString()};
  if(payload.starts_at&&payload.ends_at&&new Date(payload.ends_at)<=new Date(payload.starts_at))error("La date de fin doit être après le début.");
  if(status==="active"&&current&&current.status==="active"){ await client.from("battle_pass_seasons").update({status:"ended",updated_at:new Date().toISOString(),updated_by:String(actor||"")||null}).eq("status","active").neq("id",current.id); }
  let row;
  if(current){ const {data,e,error:ue}=await client.from("battle_pass_seasons").update(payload).eq("id",current.id).select("*").single(); if(ue)throw ue; row=data; }
  else { const {data,error:ie}=await client.from("battle_pass_seasons").insert({...payload,created_by:String(actor||"")||null}).select("*").single(); if(ie)throw ie; row=data; }
  const levels=await ensureLevels(client,row); await client.from("battle_pass_levels").update({xp_required:0}).eq("season_id",row.id).eq("level",1); for(const l of levels){ const target=(l.level-1)*row.xp_per_level; if(l.xp_required!==target) await client.from("battle_pass_levels").update({xp_required:target,updated_at:new Date().toISOString()}).eq("id",l.id); }
  return {season:row,levels:await ensureLevels(client,row)};
}
async function saveLevel(id,input,actor){ const client=db(); const {data:level,error:le}=await client.from("battle_pass_levels").select("*").eq("id",id).maybeSingle(); if(le)throw le;if(!level)error("Palier introuvable.",404); const payload={free_rewards:normalizeRewards(input.freeRewards??input.free_rewards),premium_rewards:normalizeRewards(input.premiumRewards??input.premium_rewards),updated_at:new Date().toISOString()}; const {data,error:ue}=await client.from("battle_pass_levels").update(payload).eq("id",id).select("*").single(); if(ue)throw ue; return data; }
async function addPlayer(input,actor){ const client=db(); const season=await currentSeason(client); if(!season)error("Aucune saison Battle Pass.",404); const steamId=clean(input.steamId??input.steam_id,17); if(!/^\d{17}$/.test(steamId))error("SteamID64 invalide."); const xp=Math.max(0,integer(input.xp,0)); const payload={season_id:season.id,steam_id:steamId,player_name:clean(input.playerName??input.player_name,100)||null,xp,level:computeLevel(season,xp),is_premium:Boolean(input.isPremium??input.is_premium),updated_at:new Date().toISOString()}; const {data,error:ie}=await client.from("battle_pass_players").upsert(payload,{onConflict:"season_id,steam_id"}).select("*").single(); if(ie)throw ie; await client.from("battle_pass_history").insert({season_id:season.id,player_id:data.id,steam_id:steamId,action:"player_upsert",actor_steam_id:String(actor||"")||null,new_xp:data.xp,new_level:data.level,details:{is_premium:data.is_premium}}); return data; }
async function updatePlayer(id,input,actor){ const client=db(); const {data:old,error:oe}=await client.from("battle_pass_players").select("*").eq("id",id).maybeSingle(); if(oe)throw oe;if(!old)error("Joueur introuvable.",404); const season=await seasonById(client,old.season_id); const xp=Math.max(0,integer(input.xp,old.xp)); const payload={player_name:clean(input.playerName??input.player_name??old.player_name,100)||null,xp,level:computeLevel(season,xp),is_premium:Boolean(input.isPremium??input.is_premium),updated_at:new Date().toISOString()}; const {data,error:ue}=await client.from("battle_pass_players").update(payload).eq("id",id).select("*").single(); if(ue)throw ue; await client.from("battle_pass_history").insert({season_id:old.season_id,player_id:id,steam_id:old.steam_id,action:"player_update",actor_steam_id:String(actor||"")||null,old_xp:old.xp,new_xp:data.xp,old_level:old.level,new_level:data.level,details:{old_premium:old.is_premium,new_premium:data.is_premium}}); return data; }
async function me(steamId){ const client=db(); const season=await currentSeason(client); if(!season)return{season:null,progress:null}; const {data:progress,error:pe}=await client.from("battle_pass_players").select("*").eq("season_id",season.id).eq("steam_id",String(steamId)).maybeSingle(); if(pe)throw pe; const {data:levels,error:le}=await client.from("battle_pass_levels").select("level,xp_required,free_rewards,premium_rewards").eq("season_id",season.id).order("level"); if(le)throw le; const p=progress||{steam_id:String(steamId),xp:0,level:1,is_premium:false}; const currentThreshold=(Math.max(1,p.level)-1)*season.xp_per_level; const nextThreshold=Math.min(season.max_level*season.xp_per_level,p.level*season.xp_per_level); return{season,progress:{...p,xp_in_level:Math.max(0,Number(p.xp)-currentThreshold),xp_to_next:Math.max(0,nextThreshold-currentThreshold)},levels:levels||[]}; }
module.exports={dashboard,saveSeason,saveLevel,addPlayer,updatePlayer,me};
