-- SENZANY — Base des objets DayZ
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  classname text not null,
  display_name text not null,
  category text not null default 'Autres',
  mod_name text not null default 'Inconnu',
  source_files text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists items_classname_unique
  on public.items (classname);

create index if not exists items_display_name_lower_idx
  on public.items (lower(display_name));

create index if not exists items_category_idx on public.items (category);
create index if not exists items_mod_name_idx on public.items (mod_name);

-- La table est réservée au backend utilisant la clé serveur.
alter table public.items enable row level security;


-- Droits du backend Senzany (clé service_role).
grant usage on schema public to postgres, service_role;
grant select, insert, update, delete on public.items to postgres, service_role;
grant usage, select on all sequences in schema public to postgres, service_role;

create or replace function public.set_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists items_set_updated_at on public.items;
create trigger items_set_updated_at
before update on public.items
for each row execute function public.set_items_updated_at();
