[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/game/stats"
  to = "http://213.32.88.222/api/game/stats"
  status = 200
  force = true

[[redirects]]
  from = "/api/topserveurs/stats"
  to = "/.netlify/functions/topserveurs-stats"
  status = 200

[[redirects]]
  from = "/api/discord/stats"
  to = "/.netlify/functions/discord-stats"
  status = 200

[[redirects]]
  from = "/api/steam/login"
  to = "/.netlify/functions/steam-login"
  status = 200

[[redirects]]
  from = "/api/steam/callback"
  to = "/.netlify/functions/steam-callback"
  status = 200

[[redirects]]
  from = "/api/steam/me"
  to = "/.netlify/functions/steam-me"
  status = 200

[[redirects]]
  from = "/api/steam/logout"
  to = "/.netlify/functions/steam-logout"
  status = 200

[[redirects]]
  from = "/api/discord/login"
  to = "/.netlify/functions/discord-login"
  status = 200

[[redirects]]
  from = "/api/discord/callback"
  to = "/.netlify/functions/discord-callback"
  status = 200

[[redirects]]
  from = "/api/discord/unlink"
  to = "/.netlify/functions/discord-unlink"
  status = 200
